# Generated by Django 2.1.5 on 2019-04-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
