# Generated by Django 2.1.5 on 2019-11-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20190623_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipe (Master Data)'},
        ),
        migrations.AlterModelOptions(
            name='recipeitem',
            options={'verbose_name': 'Recipe Item', 'verbose_name_plural': 'Recipe Item (Master Data)'},
        ),
    ]
