# Generated by Django 2.1.5 on 2019-11-30 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_auto_20191130_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mold',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('cavity', models.IntegerField(default=1, verbose_name='Cavity')),
                ('available', models.IntegerField(default=1, verbose_name='Available Used')),
                ('standard_weight', models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Standard weight(g)')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('draft', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='molds', to='product.Product')),
            ],
            options={
                'verbose_name': 'Mold',
                'verbose_name_plural': 'Molds',
            },
        ),
    ]
