# Generated by Django 2.1.5 on 2019-11-30 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0007_machinecapacity'),
        ('mold', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoldCapacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.IntegerField(default=0, verbose_name='Output/Day (Kgs)')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mold_capacities', to='machine.Machine')),
                ('mold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mold_capacities', to='mold.Mold')),
            ],
        ),
    ]
