# Generated by Django 2.1.5 on 2019-04-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
