# Generated by Django 2.1.5 on 2019-04-30 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_slug'),
        ('product', '0006_auto_20190426_1011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='customer.Customer'),
        ),
        migrations.AddField(
            model_name='product',
            name='fg_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Finish Goods Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Unit weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_runner',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Runner weight'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('GRAM', 'Gram'), ('KILO', 'Kilogram')], default='GRAM', max_length=10, verbose_name='Weight unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_pack',
            field=models.IntegerField(default=1, verbose_name='Pack per box'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_type',
            field=models.CharField(choices=[('CON', 'Consumable'), ('FG', 'Finish Goods'), ('SEMI', 'Semi part'), ('RAW', 'Raw Material'), ('OT', 'Other')], default='RAW', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_per_pack',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Unit per pack'),
        ),
    ]
