# Generated by Django 2.1.5 on 2019-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190505_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_warehouse_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='qty',
            field=models.IntegerField(default=0, verbose_name='On Warehouse'),
        ),
    ]
