# Generated by Django 2.1.5 on 2019-06-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190612_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='job_prefix',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Job Prefix'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_order',
            field=models.IntegerField(default=0, verbose_name='Minimum Order'),
        ),
    ]
