# Generated by Django 2.1.5 on 2019-11-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20190614_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Products - Brands'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'ordering': ['name'], 'verbose_name': 'Color', 'verbose_name_plural': 'Products - Colors'},
        ),
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Products - Groups'},
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_unit',
            field=models.CharField(choices=[('BOX', 'Box'), ('PIECE', 'Piece'), ('ROLL', 'Roll'), ('SECTION', 'Section'), ('OTHER', 'Other')], default='PIECE', max_length=10),
        ),
    ]
