# Generated by Django 2.1.5 on 2019-06-23 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('job', '0012_auto_20190623_1952'),
        ('recipe', '0006_auto_20190623_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('shifts', models.CharField(choices=[('MORNING', 'Morning'), ('NIGHT', 'Night')], default='MORNING', max_length=20)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('order_qty', models.IntegerField(default=0)),
                ('stock_qty', models.IntegerField(default=0)),
                ('final_qty', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='job.Job')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productions', to='machine.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(choices=[(1, '00-01'), (2, '01-02'), (3, '02-03'), (4, '03-04'), (5, '04-05'), (6, '05-06'), (7, '06-07'), (8, '07-08'), (9, '08-09'), (10, '09-10'), (11, '10-11'), (12, '11-12'), (13, '12-13'), (14, '13-14'), (15, '14-15'), (16, '15-16'), (17, '16-17'), (18, '17-18'), (19, '18-19'), (20, '19-20'), (21, '20-21'), (22, '21-22'), (23, '22-23'), (24, '23-00')], default=7, max_length=1)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('order_qty', models.IntegerField(default=0)),
                ('stock_qty', models.IntegerField(default=0)),
                ('final_qty', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='production.Production')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planed', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('actual', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('lot', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rawusages', to='production.Production')),
                ('recipeitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawusages', to='recipe.RecipeItem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='production',
            unique_together={('job', 'shifts')},
        ),
    ]
