# Generated by Django 2.1.5 on 2019-06-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterialusage',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
