# Generated by Django 2.1.5 on 2019-06-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_rawmaterialusage_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionhour',
            name='final_qty',
        ),
        migrations.RemoveField(
            model_name='productionhour',
            name='order_qty',
        ),
        migrations.RemoveField(
            model_name='productionhour',
            name='production_date',
        ),
        migrations.RemoveField(
            model_name='productionhour',
            name='stock_qty',
        ),
        migrations.AddField(
            model_name='productionhour',
            name='line',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AddField(
            model_name='productionhour',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productionhour',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productionhour',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productionhour',
            name='roll_min',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Roll per min'),
        ),
        migrations.AddField(
            model_name='productionhour',
            name='weight_roll',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Weight per roll'),
        ),
    ]
