# Generated by Django 2.1.5 on 2019-06-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_auto_20190624_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionhour',
            name='hour',
            field=models.IntegerField(choices=[(1, '00-01'), (2, '01-02'), (3, '02-03'), (4, '03-04'), (5, '04-05'), (6, '05-06'), (7, '06-07'), (8, '07-08'), (9, '08-09'), (10, '09-10'), (11, '10-11'), (12, '11-12'), (13, '12-13'), (14, '13-14'), (15, '14-15'), (16, '15-16'), (17, '16-17'), (18, '17-18'), (19, '18-19'), (20, '19-20'), (21, '20-21'), (22, '21-22'), (23, '22-23'), (24, '23-00')], default=7),
        ),
    ]
