# Generated by Django 2.1.5 on 2019-06-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
        ('production', '0006_scraphour'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Waste Qty')),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('productionhour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='production.ProductionHour')),
                ('waste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='waste.Waste')),
            ],
        ),
        migrations.AlterField(
            model_name='scraphour',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Scrap Qty'),
        ),
    ]
