# Generated by Django 2.1.5 on 2019-07-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('downtime', '0002_downtime_downtime_type'),
        ('production', '0007_auto_20190629_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='DowntimeHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('stop', models.TimeField(blank=True, null=True)),
                ('usage_time', models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Usage time (min)')),
                ('scrap_weight', models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Scrap weight')),
                ('waste_weight', models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Waste weight')),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('downtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='downtime.Downtime')),
                ('productionhour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='production.ProductionHour')),
            ],
        ),
    ]
