# Generated by Django 2.1.5 on 2019-07-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_downtimehour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downtimehour',
            name='scrap_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Scrap weight'),
        ),
        migrations.AlterField(
            model_name='downtimehour',
            name='usage_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Usage time (min)'),
        ),
        migrations.AlterField(
            model_name='downtimehour',
            name='waste_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Waste weight'),
        ),
    ]
