# Generated by Django 2.1.5 on 2019-11-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_auto_20190707_1356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='production',
            unique_together=set(),
        ),
    ]
