# Generated by Django 2.1.5 on 2019-11-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waste',
            options={'verbose_name': 'Waste', 'verbose_name_plural': 'Waste (Master Data)'},
        ),
    ]
