# Generated by Django 2.1.5 on 2019-05-20 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='job.Job'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='to_warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
