# Generated by Django 2.1.5 on 2019-04-26 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0002_po_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='customer.Customer'),
        ),
        migrations.AlterField(
            model_name='po',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos', to='product.Product'),
        ),
    ]
