# Generated by Django 2.1.5 on 2019-05-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0003_auto_20190426_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
