# Generated by Django 2.1.5 on 2019-06-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('po', '0004_po_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='po',
            name='po_type',
            field=models.CharField(choices=[('BUILD_TO_ORDER', 'Build to Order'), ('BUILD_TO_STOCK', 'Build to Stock')], default='BUILD_TO_ORDER', max_length=20),
        ),
    ]
