# Generated by Django 2.1.5 on 2019-07-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downtime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtime',
            name='downtime_type',
            field=models.CharField(choices=[('DOWNTIME', 'Downtime'), ('MC_OPEN', 'Setup Open Machine'), ('CHG_MODEL', 'Change Model'), ('CHG_LOGO', 'Change Logo')], default='DOWNTIME', max_length=20),
        ),
    ]
