# Generated by Django 2.1.5 on 2019-11-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downtime', '0002_downtime_downtime_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtime',
            options={'verbose_name': 'Downtime', 'verbose_name_plural': 'Downtime (Master Data)'},
        ),
    ]
