# Generated by Django 2.1.5 on 2019-11-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrap',
            options={'verbose_name': 'Scrap', 'verbose_name_plural': 'Scrap (Master Data)'},
        ),
    ]
