# Generated by Django 2.1.5 on 2019-04-26 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='po.Po'),
        ),
    ]
