# Generated by Django 2.1.5 on 2019-04-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190426_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_date', models.DateTimeField(auto_now_add=True)),
                ('qty', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completes', to='job.Job')),
            ],
        ),
    ]
