# Generated by Django 2.1.5 on 2019-04-26 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20190426_1347'),
        ('job', '0004_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='completed',
        ),
        migrations.AddField(
            model_name='job',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='recipe.Recipe'),
        ),
    ]
