# Generated by Django 2.1.5 on 2019-05-06 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_completed'),
        ('job', '0005_auto_20190426_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='po',
        ),
        migrations.AddField(
            model_name='job',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='order.Order'),
        ),
    ]
