# Generated by Django 2.1.5 on 2019-05-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_auto_20190506_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='finished_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
