# Generated by Django 2.1.5 on 2019-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20190519_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='qc_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='qc_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
