# Generated by Django 2.1.5 on 2019-06-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
        ('job', '0008_auto_20190519_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='machine.Machine'),
        ),
    ]
