# Generated by Django 2.1.5 on 2019-06-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20190623_1343'),
        ('job', '0009_job_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planed', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('actual', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawusages', to='job.Job')),
                ('recipeitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rawusages', to='recipe.RecipeItem')),
            ],
        ),
    ]
