# Generated by Django 2.1.5 on 2019-07-07 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_auto_20190623_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='job.Job'),
        ),
    ]
