# Generated by Django 2.1.5 on 2019-07-08 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_change_recipe', 'Can change Recipe'), ('can_add_output', 'Can add Output')]},
        ),
    ]
