# Generated by Django 2.1.5 on 2019-07-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_auto_20190708_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='master',
            field=models.BooleanField(default=False),
        ),
    ]
