# Generated by Django 2.1.5 on 2019-05-05 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('po', '0003_auto_20190426_1103'),
        ('product', '0008_auto_20190505_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PoMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='po.Po')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pos',
            field=models.ManyToManyField(through='order.PoMembership', to='po.Po'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='product.Product'),
        ),
    ]
