# Generated by Django 2.1.5 on 2019-05-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190505_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='po',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='po.Po'),
        ),
    ]
