# Generated by Django 2.1.5 on 2019-05-06 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190505_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='order.Order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='po',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='po.Po'),
        ),
    ]
