# Generated by Django 2.1.5 on 2019-05-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190506_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
