# Generated by Django 2.1.5 on 2019-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
