# Generated by Django 2.1.5 on 2019-06-09 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190512_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
    ]
