# Generated by Django 2.1.5 on 2019-07-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_order_qty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('can_add_po', 'Can add PO to Order'), ('can_remove_po', 'Can remove po from Order'), ('can_create_job', 'Can Create/Start Job'), ('can_delete_job', 'Can Delete Job')]},
        ),
    ]
